FROM node:22

WORKDIR /app

RUN corepack enable
RUN corepack prepare pnpm@10.15.0 --activate

COPY . .

RUN pnpm install --no-frozen-lockfile

RUN pnpm run build

EXPOSE 4173

CMD ["pnpm", "run", "serve"]
