kind = "web"
previewPath = "/"
title = "Leveling Bot"
version = "1.0.0"
id = "artifacts/leveling-bot"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18465

[services.development]
run = "pnpm --filter @workspace/leveling-bot run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/leveling-bot", "run", "build" ]
serve = "static"
publicDir = "artifacts/leveling-bot/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18465"
BASE_PATH = "/"
